name: Python Package CI

# Triggers the workflow on push or pull requests to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    # Define the environment to run the job (latest Ubuntu)
    runs-on: ubuntu-latest

    # Define a matrix to test multiple Python versions
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # Step 3: Install dependencies (using setup.py)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .

    # Step 4: Run the tests
    - name: Run tests
      run: |
        python -m unittest discover -s tests
